---
- name: Install required packages
  become: yes
  apt:
    name:
      - acl
      - aptitude
      - cifs-utils
      - cloud-guest-utils
      - cloud-init
      - cloud-utils
      - curl
      - dnsutils
      - git
      - htop
      - libsasl2-modules
      - mlocate
      - needrestart
      - net-tools
      - pwgen
      - qemu-guest-agent
      - resolvconf
      - tuned
      - tuned-utils
      - tuned-utils-systemtap
      - unattended-upgrades
      - unzip
    state: present