---
- name: Set variables
  set_fact:
    POSTFIX_DOMAIN: "{{ MYDOMAIN }}"
    HOST: "{{ ansible_hostname }}"
    FROM_EMAIL: "{{ ansible_hostname }}@{{ MYDOMAIN }}"

- name: Install Postfix, openssl, and libsasl2-modules
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - openssl
    - libsasl2-modules
  become_user: root

- name: Configure Authentication files
  copy:
    content: "{{ POSTFIX_RELAY }} {{ POSTFIX_USER }}:{{ POSTFIX_PASS }}"
    dest: /etc/postfix/sasl_passwd
    mode: '0600'
  become_user: root

- name: Configure sender maps
  copy:
    content: |
      /.+/    {{ FROM_EMAIL }}
    dest: /etc/postfix/sender_canonical_maps
  become_user: root

- name: Configure header check
  copy:
    content: |
      /From:.*/ REPLACE From: {{ FROM_EMAIL }}
    dest: /etc/postfix/header_check
  become_user: root

- name: Hash files
  command: postmap /etc/postfix/sasl_passwd
  become_user: root

- name: Secure files
  file:
    path: "{{ item }}"
    mode: '0600'
  with_items:
    - /etc/postfix/sasl_passwd
    - /etc/postfix/sasl_passwd.db
  become_user: root

- name: Configure Postfix
  command: "{{ item }}"
  with_items:
    - postconf -e "myhostname={{ HOST }}"
    - postconf -e "mydestination=\$myhostname, localhost.{{ MYDOMAIN }}, localhost"
    - postconf -e "mynetworks=127.0.0.0/8"
    - postconf -e "inet_interfaces=loopback-only"
    - postconf -e "relayhost={{ POSTFIX_RELAY }}"
    - postconf -e "smtp_use_tls=yes"
    - postconf -e "smtp_sasl_auth_enable=yes"
    - postconf -e "smtp_sasl_security_options="
    - postconf -e "smtp_sasl_password_maps=hash:/etc/postfix/sasl_passwd"
    - postconf -e "smtp_tls_CAfile=/etc/ssl/certs/Entrust_Root_Certification_Authority.pem"
    - postconf -e "smtp_tls_session_cache_timeout=3600s"
    - postconf -e "readme_directory=no"
    - postconf -e "smtp_tls_security_level=may"
    - postconf -e "sender_canonical_classes=envelope_sender, header_sender"
    - postconf -e "sender_canonical_maps=regexp:/etc/postfix/sender_canonical_maps"
    - postconf -e "smtp_header_checks=regexp:/etc/postfix/header_check"
  become_user: root

- name: Reload Postfix
  command: postfix reload
  become_user: root

# - name: Install bsd-mailx
  # apt:
    # name: bsd-mailx
    # state: present
  # become_user: root

# - name: Send Test email
  # command: echo "Configuration Works" | mail -s "Working Config" {{ POSTFIX_USER }}
  # become_user: root
